In [16]:
# PANDA SERIES

PANDA SERIES

In [17]:
import pandas as pd
import numpy as np

In [18]:

# Series from Lists have index a

country=["Baladesh","India"]
pd.Series(country)

0    Baladesh
1       India
dtype: object

In [19]:
runs=[10,56,100]

pd.Series(runs)

0     10
1     56
2    100
dtype: int64

In [20]:
#costom index
marks=[67,67,135]
subjects=["English","Hindi","aths"]
pd.Series(marks,index=subjects)

English     67
Hindi       67
aths       135
dtype: int64